apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
  namespace: dev
  labels:
    app: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: wil42/playground:v2  # ← Change to v2 as needed
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-service
spec:
  selector:
    app: playground
  ports:
  - port: 8888
    targetPort: 8888
  type: ClusterIP
